FROM ubuntu:22.04
LABEL ubuntu_version=22.04
ARG DEBIAN_FRONTEND=noninteractive

# use this Dockerfile for revisions of lighttpd2 from c8bf635 onwards (>28/02/2021)

RUN apt-get update && apt-get install -y \
	sudo \
	build-essential \
	autoconf \
	automake \
	libtool \
	git \
	curl \
	openssh-server \
	--no-install-recommends

RUN apt-get install -yq --reinstall ca-certificates

# Fix lighttpd2:22 in the same manner as curl etc.
RUN cd /tmp && curl -L https://github.com/linux-test-project/lcov/releases/download/v1.16/lcov-1.16.tar.gz | tar xz && cd lcov-* && make PREFIX=/usr install
RUN cd /tmp && curl -L http://downloads.sourceforge.net/project/cloc/cloc/v1.64/cloc-1.64.tar.gz | tar xz && cd cloc-* && curl -L https://bugs.archlinux.org/task/45494?getfile=13174 > cloc.1.64.patch && patch -p1 < cloc.1.64.patch && make install

# Remove the old version of gcc
RUN apt-get remove gcc -y

RUN sudo apt install software-properties-common -y
RUN sudo add-apt-repository ppa:ubuntu-toolchain-r/test
RUN sudo apt update -y && sudo apt install gcc-9 -y
# Symbolic link between gcc-9, gcov-9 to gcc, gcov
RUN sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 100
RUN sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-9 100

RUN mkdir -p /var/run/sshd

RUN mkdir /root/.ssh
ADD id_rsa.pub /root/.ssh/authorized_keys
RUN chown -R root:root /root/.ssh
RUN chmod -R 700 /root/.ssh

RUN echo "root:root" | chpasswd

RUN apt-get install -yq \
	libglib2.0-dev \
	libev-dev \
	libssl-dev \
    libgnutls28-dev \
	zlib1g-dev \
	libbz2-dev \
	liblua5.1-dev \
	ragel \
    libunwind-dev \
    libidn11-dev \
    librtmp-dev \
    libcurl4-gnutls-dev # or libcurl4-openssl-dev

RUN apt-get -yq install python3-pip
RUN pip3 install pycurl

RUN git clone https://github.com/lighttpd/lighttpd2.git /home/lighttpd2
ADD measure-cov.sh /root/

# We have both python2 and python3 installed, so we need to make sure that we use python3
RUN echo "alias python=python3" >> /root/.bashrc

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
