# Ubuntu 14.04 comes with gcc 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.4), and original data was collected with gcc 4.7.2 (Ubuntu/Linaro 4.7.2-2ubuntu1) (consulting coverage archives' build_info files).

FROM ubuntu:14.04

RUN apt-get update && apt-get install -y \
	sudo \
	build-essential \
	autoconf \
	automake \
	libtool \
	git \
	curl \
	openssh-server \
    realpath \
	--no-install-recommends

RUN cd /tmp && curl -L http://downloads.sourceforge.net/ltp/lcov-1.10.tar.gz | tar xz && cd lcov-* && make install
RUN cd /tmp && curl -L http://downloads.sourceforge.net/project/cloc/cloc/v1.64/cloc-1.64.tar.gz | tar xz && cd cloc-* && make install
#RUN cd /tmp && curl -L -k https://download.libsodium.org/libsodium/releases/old/unsupported/libsodium-1.0.0.tar.gz | tar xz && cd libsodium-* && ./configure && make && make check && make install && ldconfig


RUN mkdir -p /var/run/sshd

RUN mkdir /root/.ssh
ADD id_rsa.pub /root/.ssh/authorized_keys
RUN chown -R root:root /root/.ssh
RUN chmod -R 700 /root/.ssh

RUN echo "root:root" | chpasswd

RUN apt-get install -yq --reinstall ca-certificates

RUN git clone https://github.com/zeromq/zeromq4-x.git /home/zeromq4-x/
ADD measure-cov.sh /root/

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
