FROM ubuntu:18.04
LABEL ubuntu_version=18.04
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
	sudo \
	build-essential \
	autoconf \
	automake \
	libtool \
	git \
	curl \
	openssh-server \
    lcov \
	--no-install-recommends

#RUN cd /tmp && curl -L http://downloads.sourceforge.net/ltp/lcov-1.10.tar.gz | tar xz && cd lcov-* && make install
RUN cd /tmp && curl -L http://downloads.sourceforge.net/project/cloc/cloc/v1.64/cloc-1.64.tar.gz | tar xz && cd cloc-* && make install

RUN mkdir -p /var/run/sshd

RUN mkdir /root/.ssh
ADD id_rsa.pub /root/.ssh/authorized_keys
RUN chown -R root:root /root/.ssh
RUN chmod -R 700 /root/.ssh

RUN echo "root:root" | chpasswd

RUN adduser --gecos "" --disabled-password regular

RUN apt-get -yq install libncurses5-dev libncursesw5-dev libtool-bin clang
# Clang takes up a lot of space unfortunately

RUN apt-get install -yq --reinstall ca-certificates

RUN git clone https://github.com/vim/vim.git /home/vim

RUN chown -R regular /home/vim
RUN git config --global --add safe.directory /home/vim

RUN apt-get install -yq libxt-dev libgtk-3-dev --no-install-recommends

ADD measure-cov.sh /root/

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
