name: Run tests
run-name: Tests run by @${{ github.actor }}
on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - master
      - dev
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: init
        run: pwd && echo "Hello"
      
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
      
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
        
      - name: Install Python requirements
        run: pip install fabric==2.7.1 docker
        
      - name: Set up docker (1)
        uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      
      - name: Set up docker (2)
        run: |
          set -x

          docker version

          docker run --rm hello-world
      
      - name: Install GNU parallel
        run: sudo apt-get install -y parallel
        
      - name: Copy private ssh key to .ssh
#           working-directory: 
        run: pwd && mkdir -p ~/.ssh && ${{ secrets.SSH_KEY }} > ~/.ssh/id_rsa && ls ~/.ssh

      - name: Run tests
        run: chmod a+x tests/runtests.sh && ./tests/runtests.sh && cat tests/tests-offline.log && cat tests/tests-online.log

