name: Run tests
run-name: Tests run by @${{ github.actor }}
on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
#   push:
#     branches:
#       - dev

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
      
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
        
      - name: Install Python requirements
        run: pip install fabric==2.7.1 docker
        
      - name: Set up docker (1)
        uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      
      - name: Set up docker (2)
        run: |
          set -x

          docker version

          docker run --rm hello-world
      
      - name: Install GNU parallel
        run: sudo apt-get install -y parallel
        
      - name: Install lcov
        run: sudo apt-get install -y lcov

      - name: Install cloc
        run: cd /tmp && curl -L http://downloads.sourceforge.net/project/cloc/cloc/v1.64/cloc-1.64.tar.gz | tar xz && cd cloc-* && curl -L https://bugs.archlinux.org/task/45494?getfile=13174 > cloc.1.64.patch && patch -p1 < cloc.1.64.patch && sudo make install
        
      - name: Copy private ssh key to .ssh
        run: pwd && mkdir -p ~/.ssh && echo "$PRIVATE_SSH_KEY" > ~/.ssh/id_rsa && ls ~/.ssh
        env:
          PRIVATE_SSH_KEY: ${{ secrets.SSH_KEY }}
          
      - name: Clone Binutils (Test repo)
        run: git clone git://sourceware.org/git/binutils.git repos/binutils

      - name: Run tests
        run: chmod a+x tests/runtests.sh && ./tests/runtests.sh
        
      - name: Display logs on failure
        if: failure()
        run: cat tests/logs/tests-offline.log && cat tests/logs/tests-online.log

